CONFIG += qt debug
HEADERS += MainWindow.hpp
HEADERS += GlobalState.hpp
HEADERS += Network.hpp
HEADERS += syncNetwork.hpp
SOURCES += main.cpp
SOURCES += Mainwindow.cpp
SOURCES += Network.cpp
SOURCES += syncNetwork.cpp
SOURCES += GlobalState.cpp